version: '3.8'

services:
  week6task:
    image: week6task
    build:
      context: task-one
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4444:4444
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/index.js"]
