version: '3.8'

services:
  week6task:
    image: week6task
    build:
      context: task-one
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4444:4444
